"""Add class_student table

Revision ID: 017_add_class_student
Revises: edde780bb399
Create Date: 2026-02-28 05:15:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "017_add_class_student"
down_revision: str | Sequence[str] | None = "edde780bb399"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "class_students",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="主键ID"),
        sa.Column("class_id", sa.Integer(), nullable=False, comment="班级ID"),
        sa.Column("student_id", sa.Integer(), nullable=False, comment="学生ID"),
        sa.Column(
            "enrolled_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="入学时间",
        ),
        sa.Column(
            "enrollment_status",
            sa.String(length=20),
            nullable=False,
            comment="入学状态",
        ),
        sa.Column("enrolled_by", sa.Integer(), nullable=True, comment="注册人ID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="更新时间",
        ),
        sa.ForeignKeyConstraint(["class_id"], ["classes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["enrolled_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("class_id", "student_id", name="idx_class_student_unique"),
        sa.Index("idx_class_students_class_id", "class_id"),
        sa.Index("idx_class_students_student_id", "student_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("class_students")
    # ### end Alembic commands ###
