"""课程管理模块schemas."""

from .assignment_schemas import (
    AssignmentHistory,
    BulkAssignmentRequest,
    BulkAssignmentResponse,
    CourseAssignmentRequest,
    CourseAssignmentResponse,
    QualificationCheckResult,
    TeacherQualificationCheck,
    TeacherWorkloadInfo,
    TimeConflictCheck,
    TimeConflictResult,
    WorkloadBalanceRequest,
    WorkloadBalanceResponse,
)
from .class_schemas import (
    ClassBatchCreate,
    ClassConflictCheck,
    ClassCreate,
    ClassListResponse,
    ClassResponse,
    ClassStatistics,
    ClassUpdate,
    ConflictCheckResult,
    StudentEnrollmentRequest,
    StudentEnrollmentResponse,
)
from .course_schemas import (
    ClassBase,
    CourseCreate,
    CourseListResponse,
    CourseResponse,
    CourseStatusUpdate,
    CourseTemplateCreate,
    CourseTemplateListResponse,
    CourseTemplateResponse,
    CourseTemplateUpdate,
    CourseUpdate,
    CourseVersionResponse,
)

__all__ = [
    # 课程相关schemas
    "CourseCreate",
    "CourseUpdate",
    "CourseResponse",
    "CourseListResponse",
    "CourseStatusUpdate",
    "CourseVersionResponse",
    "CourseTemplateCreate",
    "CourseTemplateUpdate",
    "CourseTemplateResponse",
    "CourseTemplateListResponse",
    # 班级相关schemas
    "ClassBase",
    "ClassCreate",
    "ClassUpdate",
    "ClassResponse",
    "ClassListResponse",
    "ClassBatchCreate",
    "ClassConflictCheck",
    "ConflictCheckResult",
    "ClassStatistics",
    "StudentEnrollmentRequest",
    "StudentEnrollmentResponse",
    # 分配管理schemas
    "CourseAssignmentRequest",
    "CourseAssignmentResponse",
    "TeacherQualificationCheck",
    "QualificationCheckResult",
    "TeacherWorkloadInfo",
    "WorkloadBalanceRequest",
    "WorkloadBalanceResponse",
    "TimeConflictCheck",
    "TimeConflictResult",
    "BulkAssignmentRequest",
    "BulkAssignmentResponse",
    "AssignmentHistory",
]
